C++/p001-Basic-Neuron-3-inputs.cpp
Implementation of code from P.1 in C++
=> p001 in C++

Java/p001-Basic-Neuron-3-inputs.java
Created a neuron with 3 inputs in the Java programming language
=> Added Java Neuron

C++/p001-Basic-Neuron-3-inputs.cpp, Rust/p001-Basic-Neuron-inputs.rs
Creating a neuron using Rust language
=> Adding Rust neuron

PHP/p001-Basic-Neuron-3-inputs.php, PHP/p002-Basic-Neuron-Layer.php
=> PHP version

C++/p001-Basic-Neuron-3-inputs.cpp, C++/p002-Basic-Neuron-Layer.cpp
p002 implemented in C++
Also changed input values back in p001 file to be the same as the book.
Might be worth doing the same for other languages
=> Added p002 & updates values from p001

Rust/p001-Basic-Neuron-3-inputs.rs, Rust/p002-Basic-Neuron-Layer.rs
Also renamed p001 to match the rest of the languages and update values in p001 to match book.
=> added p002 for rust lang

GDscript/p001-Basic-Neuron-3-inputs.gd, GDscript/p002-Basic-Neuron-Layer.gd, PowerShell/p001-Basic-Neuron-3-inputs.ps1, PowerShell/p002-Basic-Neuron-Layer.ps1
I have added code in GDscript (used in Godot game engine) and PowerShell. To keep code consistent, I have used the variable values shown in the p002 tutorial video (aligns with the book).
=> adding p001 and p002 code in GDscript and PowerShell

C/p001-Basic-Neuron-3-inputs.c, C/p002-Basic-Neuron-Layer.c, Go/P001-Basic-Neuron-3-inputs.go, Go/p002-Basic-Neuron-Layer.go, Lua/p001-Basic-Neuron-3-inputs.lua, Lua/p002-Basic-Neuron-Layer.lua
Hello, just made the corresponding code for each language
=> Go, C and Lua implementations

D/p001_Basic_Neuron_3_inputs.d, D/p002_Basic_Neuron_Layer.d, D/p003_Dot_Product.d
Added code for the D Programming Language for the first three lessons on YouTube.
=> adding code for the d programming language

AVR_Assembly/attiny85.asm, AVR_Assembly/p001-Basic-Neuron-3-inputs.asm, AVR_Assembly/tasks.json, AVR_Assembly/template.asm
I try to implement the neural network in assembly for avr.
More specific for an Attiny85.
There is not even a multiply function, so this is a challenge.
Only integer values are supported.
=> Initial commit for avr assembly. Need help!

R/p002.r
R has weird indexing. It starts at 1 for some reason. I think the creators were high on computer crack
=> Because p001.r needs a companion in life

Swift/p001-Basic-Neuron-3-inputs.swift, Swift/p002-Basic-Neuron-Layer.swift, Swift/p003-Dot-Product.swift
The `dot()` and `add()` functions weren't implemented with error-handling and dimension-checking as to not clutter up the code for those looking to learn (as I annotated in the code itself)
If there's anything you'd like me to add/change/fix feel free to let me know :)
ps: I love this initiative you have here. I myself started working on a similar idea with [perceptrons in different languages](https://github.com/DelSquared/Perceptron-Model-in-Different-Programming-Languages) in the past but never got to finish it due to not having any crowd sourcing capabilities. I'm very happy to be able to contribute here :)
ps2: As a suggestion, could you maybe make a note of [repl](https://repl.it/languages) in the readme? It's an easy place where anyone can easily try out these different-language …
=> Swift code p001-p003

C/p001-Basic-Neuron-3-inputs.c, C/p002-Basic-Neuron-Layer.c, C/p003-Dot Product.c
Code to calculate the dot product for part 3.
Changed the previous tutorial datatypes to double for better resolution
=> C code P.3 The Dot Product

C#/p001-Basic-Neuron-3-inputs.cs, C#/p002-Basic-Neuron-Layer.cs, C#/p003-Dot-Product.cs
1. Added C# folder
2. Included code for Simple Neuron with 4 Inputs, Simple Layer with 3 Neurons and Dot Product calculation in C# using Accord.Net Math for Dot Product Calculation.
=> C# Code Initial Commit

Java/P001BasicNeuron3Inputs.java, Java/P002BasicNeuronLayer.java, Kotlin/P001BasicNeuron3Inputs.kt, Kotlin/P002BasicNeuronLayer.kt, Kotlin/P003DotProduct.kt, MATLAB/p001-Basic-Neuron-3-Inputs.m, MATLAB/p002-Basic-Neuron-Layer.m, MATLAB/p003-Dot-Product.m
- MATLAB codes are added
- Issues at P002BasicNeuronLayer.java and P001BasicNeuron3Inputs.java have fixed
=> MATLAB codes are added and java code fixed

Julia/p001-Basic-Neuron-3-inputs.jl, Julia/p002-Basic-Neuron-Layer.jl, Julia/p003-Dot-Product.jl
Wrote the scripts from the first three lessons in Julia.
=> Let's also do this in Julia

Rust/p003-Dot-Product.rs
Will likely start using ndarray package to assist with linear math
=> adding p003 for rust-lang

Awk/p001-Basic-Neuron-3-inputs.awk, Awk/p002-Basic-Neuron-Layer.awk
Note, if ya want the more complex examples that respond to command-line parameters within the [`awk-utilities/machine-learning-examples`](https://github.com/awk-utilities/machine-learning-examples) repository too, then feel free to request'em
=> Adds Awk scripts

Crystal/p001-Basic-Neuron-3-inputs.cr, Crystal/p002-Basic-Neuron-Layer.cr, Crystal/p003-Dot-Product.cr, Cuda/p001-Basic-Neuron-3-inputs.cu, Cuda/p002-Basic-Neuron-Layer.cu, Cuda/p003-Dot-Product.cu
Here's a language that generally falls under the radar that my hipster university buddies really liked back in 2015 (More info on the [wiki](https://en.wikipedia.org/wiki/Crystal_(programming_language)))
With regards to Cuda, the code works but currently it's a bit spaghetti-like. If anyone has any suggestions on how to make the initialisation of `inputs`, `weights` and `bias` a bit cleaner and more readable I'll be happy to include the change (especially for p002 and p003 because they are the worst offenders)
=> Crystal and Cuda code p001-p003

Actionscript3/P001BasicNeuron3Inputs.as
P001BasicNeuron3Inputs Actionscript3
=> P001BasicNeuron3Inputs Actionscript3

Actionscript3/P002BasicNeuronLayer.as
P002BasicNeuronLayer Actionscript 3
=> P002BasicNeuronLayer Actionscript 3

Actionscript3/P003DotProduct.as
=> P003DotProduct Actionscript 3

Ruby/p001_Basic_Neuron_3_inputs.rb, Ruby/p002_Basic_Neuron_Layer.rb, Ruby/p003_Dot_Product.rb
=> Ruby programming

Fortran/p001-Basic-Neuron-3-inputs.f90, Fortran/p004-Layers-and-Object.f90
I was scared of this part, I'm actually a beginner in Fortran (1 Month experience) and when i saw the class in the video I was terrified that i fail, but now I think that Fortran has a very natural syntax (more verbose though)
I tested the program by first creating the objects then overwriting the random weights with the weights in the tutorial (before deleting/adding class) and it matched :D, so we are on the same page
=> Added the fourth Fortran code

GDscript/p003-Dot-Product.gd, PowerShell/p003-Dot-Product.ps1
Custom functions are included to calculate dot product and adding same sized arrays.
=> Adding p003 in PowerShell. 

D/p004_Layers_and_Object.d
This is the D code for the p004 section corresponding to the YT tutorials.
I included unittests to make sure that everything was working similarly to how it does in python, since the Numpy seeding is different from the D Language seeding.
=> adding new D code for p004_Layers_and_Object

Lua/p003-Dot-Product.lua
Let me know if anything can be improved.
Here's part 3 of the video in Lua.
=> Added part 3 - Dot Product in Lua

Julia/p004-Layers-And-Struct.jl
p004 in Julia using a struct instead of an object.
=> p004 in Julia

OCaml/bin/dot_product.ml, OCaml/bin/dune, OCaml/bin/layers.ml, OCaml/bin/main.ml, OCaml/bin/p002.ml
A version in Ocaml. All four parts are available. You need dune and ppx_deriving to run .
=> Ocaml version

Julia/p004-Layers-And-Struct.jl, Julia/p005-ReLU-Activation.jl
Changed p004 to use pure functions, which (I recently found out) is more in line with how Julia wants to be used. Then I added p005.
=> P005 in Julia

Dart/P001_Basic_Neuron_3_Input.dart, Dart/P002_BasicNeuronLayer.dart, Dart/P003_Dot_Product.dart, Kotlin/P001BasicNeuron3Inputs.kt, Kotlin/P002BasicNeuronLayer.kt, Kotlin/P003DotProduct.kt
Following changes were made in this pull request:
1. fun main() was missing in P001BasicNeuron3Inputs.kt and P002BasicNeuronLayer.kt. So I also fixed those files.
2. Dot Product for Kotlin is added
3. Dart Programming Language added (along with all Dart codes).
=> Dot Product in Kotlin

Elixir/p001_basic_neurons_3_inputs.ex, Elixir/p002_basic_neuron_layer.ex, Elixir/p003_dot_product.ex
=> elixir code

.gitignore, Swift/p003-Dot-Product.swift
I liked the provided code, but noticed in the material we actually covered zip as composing a dot product ... zip is a native method in swift too!
=> somewhat more swift-y syntax

VB.NET/p001-Basic-Neuron-3-inputs.vb, VB.NET/p002-Basic-Neuron-Layer.vb, VB.NET/p003-Dot-Product.vb
Added VB.NET source for the first 3 videos. The third file utilizes Accord.Math.
https://www.nuget.org/packages/Accord.Math/3.8.2-alpha
=> Added first 3 videos VB.NET

Java/P004LayersAndObjects.java, Java/P005ReLUActivationAndSpiralDataset.java
Java implementation of part 4 of Neural Networks from Scratch.
=> Create P004LayersAndObjects.java and P005ReLUActivationAndSpiralDataset.java

Javascript/spiral-data.js
converted @shreeviknesh's spiral data function in #106 from cpp to js
=> Add spiral-data function for JavaScript

C#/p005-ReLU-Activation_with_Spiral_Data.cs
Added Spiral Dataset data from tutorial p005 to C#
use MathNet.Numerics to handle vector and matrix operations.
=> p005-ReLU-Activation_Spiral_Dataset C#

C#/p005-ReLU-Activation.cs
Fix spiral_data to match the Python implementation by using Standard distribution instead of Uniform distribution.
=> C# spiral_data implementation fix
